version: '3'
services:
  db:
    build:
      context: .
      dockerfile: mongo.dockerfile
    expose:
      - "27017"
    networks:
      - app-network

  messaging-service:
    restart: always
    container_name: messaging-service
    build:
      context: ./backend/messaging-service
      dockerfile: Dockerfile
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./drillagent:/data
    environment:
      - JAVA_TOOL_OPTIONS="-agentpath:/data/libdrill_agent.so=drillInstallationDir=/data,adminAddress=host.docker.internal:9090,agentId=messagingServiceAgent,groupId=test,buildVersion=0.1.0,logLevel=TRACE"

  notifications-service:
    restart: always
    container_name: notifications-service
    build:
      context: ./backend/notifications-service
      dockerfile: Dockerfile
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    restart: always
    build:
      context: .
      dockerfile: nginx.dockerfile
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      - messaging-service
      - notifications-service
    environment:
      JS_AGENT_HOST: ${JS_AGENT_HOST}
      JS_AST_PARSER_VERSION: ${JS_AST_PARSER_VERSION}
      BUILD_VERSION: ${FE_BUILD_VERSION}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
